version: '3.7'

services:
  ubuntu:
    image: jlvihv/cairo-anaconda-env:0.1.1
    container_name: cairo-python-env
    volumes:
      - ./compile.sh:/compile.sh
      - ./cairo-project:/cairo-project
    environment:
      - STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
      - STARKNET_NETWORK=alpha-goerli
    command: bash compile.sh